### PR TITLE
Release 1.0.1

### PR DESCRIPTION
**Pull request by gsmet**

### CODE REVIEW

**Comment by gsmet** [comment]
@michael-simons so this is how you release. You need to do that in a PR from a branch that is in this repository (not a fork!), then you wait for the Prerelease workflow to be finished, you merge the PR and you can have a look at the release workflow in the `Actions` tab. The artifacts are released and pushed to Central automatically from there.

**Comment by michael-simons** [comment]
Thanks, @gsmet That's just great.
So just changing the properties? 
Does the PR title matter? Probably, right?

Thanks a lot for the effort put into the Quarkiverse. Right now, feels like the way forward (especially because my memory is fresh about having the 2.5.3 bugfix for the Neo4j extension in my head that made me build the whole Quarkus).

**Comment by gsmet** [comment]
No, title is not important. The important part is to update both versions and to create a branch that is in this very repo. And to wait for the Pre release task to be finished.

**Comment by gsmet** [comment]
You have all the details here: https://github.com/quarkiverse/quarkiverse/wiki/Release#perform-the-release .

BTW, I publish the ITs because maybe at some point the extension will be part of a Platform and we want to have tests around then.

**Pull request merged**
