### PR TITLE
Add symbolic link to examples

### PR DESCRIPTION
**Pull request by gastaldi**
See https://docs.antora.org/antora/latest/symlinks/ for details

### CODE REVIEW

**Review by michael-simons — APPROVED** [review]

**Comment by gastaldi** [comment]
Hm, the maven build didn't like it, let me investigate why

**Comment by gastaldi** [comment]
@LightGuard is this a known issue with the asciidoctor maven plugin?

**Comment by gastaldi** [comment]
I created https://github.com/asciidoctor/asciidoctor-maven-plugin/issues/588 to track this

**Comment by gastaldi** [comment]
@michael-simons I skipped the asciidoctor-maven-plugin execution for now in [`34a42e6` (#83)](https://github.com/quarkiverse/quarkus-neo4j/pull/83/commits/34a42e6e688feaffd95bebbad5dd56a6975a86c5). 

Since the docs are generated through Antora, that shouldn't be a big issue, but it's up to you to decide if this should be merged or not 😉

**Comment by gsmet** [comment]
I have a setup that works here:
- https://github.com/quarkiverse/quarkus-github-app/blob/main/docs/templates/includes/attributes.adoc for the attribute
- https://raw.githubusercontent.com/quarkiverse/quarkus-github-app/main/docs/modules/ROOT/pages/commands.adoc for the actual includes
- https://github.com/quarkiverse/quarkus-github-app/tree/main/docs/modules/ROOT/examples/command/airline for the source code
- https://github.com/quarkiverse/quarkus-github-app/blob/main/docs/pom.xml#L29 to actually get things compiled and validated by Maven

**Comment by gastaldi** [comment]
Using @gsmet's example above I managed to make it work (but without compiling, since it would require setting the dependencies and put in the expected packages). 

I think we can add the `examplesdir` attribute in the quarkiverse-parent pom.xml to make configuration easier, WDYT?

**Comment by gsmet** [comment]
I /think/ I included this new stuff in the template.

**Comment by gastaldi** [comment]
@gsmet that's right, you did, but https://github.com/quarkusio/quarkus/blob/main/independent-projects/tools/base-codestarts/src/main/resources/codestarts/quarkus-extension/code/quarkiverse/java/docs/pom.tpl.qute.xml#L28 assumes that everything under the `examples/` is compilable, which may not be necessarily true

**Comment by gsmet** [comment]
Yeah, for me, the whole point of that was to have compilable examples. If not compilable, better add them directly in the doc and not bother about creating external files.

**Comment by gastaldi** [comment]
They are already compiled when the integration tests are executed, so the idea is to just reference them in the docs instead of having it copied somewhere

**Comment by abelsromero** [comment]
I answered https://github.com/asciidoctor/asciidoctor-maven-plugin/issues/588 but reading this I am confused. This repo is crearly and Antora module, it doesn't make sense to use the asciidoctor maven plugin unless you are reusing pieces of docs somehow. Which I would not recommend, Antora adds many things on top and we cannot support them unless we build a full reimplementation.

**Comment by gsmet** [comment]
@abelsromero so basically, we are using the Maven plugin to get some local rendering to check the output. Except for that, we don't use it.

And the modules of several repositories are then aggregated into a single Antora website.

So our general aim is to have both outputs working so that people can check the output in their local repo before pushing it.

**Comment by abelsromero** [comment]
Thanks @gsmet I'll integrate that into our story, there may be something we can do to support this preview scenario 🙇 .

**Comment by michael-simons** [comment]
@all-contributors please add @gastaldi  for infra

**Pull request merged**
