### PR TITLE
Add link to new4j browser on the Dev UI (if started by Dev Services)

### PR DESCRIPTION
**Pull request by phillip-kruger**
As discussed in the insights, this PR will add a link to the neo4j browser in Dev UI.

Peek 2022-02-15 21-27

Signed-off-by:Phillip Kruger <phillip.kruger@gmail.com>

### CODE REVIEW

**Comment by phillip-kruger** [comment]
cc @michael-simons

**Review by michael-simons — APPROVED** [review]
Sweet! Thank you.

**Comment by michael-simons** [comment]
@all-contributors please add @phillip-kruger

**Comment by michael-simons** [comment]
@all-contributors please add @phillip-kruger for code

**Pull request merged**
